source = ./colors.conf

################
### MONITORS ###
################

source = ~/.config/hypr/config/hyprland/monitors.conf

#############################
### ENVIRONMENT VARIABLES ###
#############################

source = ~/.config/hypr/gum-theme.conf
source = ~/.config/hypr/config/hyprland/envs.conf

#############
### INPUT ###
#############

source = ~/.config/hypr/config/hyprland/input.conf

#################
### AUTOSTART ###
#################

source = ~/.config/hypr/config/hyprland/gtk.conf
source = ~/.config/hypr/config/hyprland/autostart.conf

###################
### KEYBINDINGS ###
###################

source = ~/.config/hypr/config/hyprland/keybindings.conf

#####################
### LOOK AND FEEL ###
#####################

source = ~/.config/hypr/config/hyprland/look-and-feel.conf

##############################
### WINDOWS AND WORKSPACES ###
##############################

source = ~/.config/hypr/config/hyprland/windows.conf