# Set GTK application styles using gsettings
exec-once = gsettings set org.gnome.desktop.interface icon-theme 'Adwaita'
exec-once = gsettings set org.gnome.desktop.interface cursor-theme 'Adwaita'
exec-once = gsettings set org.gnome.desktop.interface font-name 'CommitMono Nerd Font 12'