--format bestaudio
--extract-audio
--audio-format mp3
--audio-quality 0 # VBR máxima calidade (~256 kbps de media)
# Cambiar fecha dos metadatos a YYYY-MM-DD
--parse-metadata "upload_date:%(meta_date)s"
--replace-in-metadata "meta_date" "(.{4})(.{2})(.{2})" "\1-\2-\3"
# Cambiar artistas dos metadatos a Artist 1; Artist 2; ...
--parse-metadata "artists:%(meta_artist)s"
--replace-in-metadata "meta_artist" "\[|\]|'" ""
--replace-in-metadata "meta_artist" "," ";"
--parse-metadata "meta_artist:%(meta_album_artist)s"
# Cambiar índice de pista dos metadatos a 1, 2, 3...
--parse-metadata "playlist_index:%(meta_track)s"
--embed-metadata
--embed-thumbnail
--ppa "ffmpeg:-id3v2_version 4"
--output "$HOME/Música/yt-dlp/%(artists.0)s/%(album)s/%(playlist_index)s. %(title)s.%(ext)s"
--retries 5
--retry-sleep 10