[bar]
order = [ "default" ]

    [bar.default]
    background_opacity = 1
    capsule_thickness = 0.8
    start = [ "clock", "launcher", "wallpaper", "mpvpaper", "system_update" ]
    center = [ "workspaces" ]
    end = [
        "media",
        "tray",
        "notifications",
        "clipboard",
        "network",
        "bluetooth",
        "volume",
        "brightness",
        "battery",
        "session"
    ]
    font_family = "Adwaita Sans"
    margin_edge = 0
    margin_ends = 0
    padding = 15
    radius = 0
    radius_bottom_left = 20
    radius_bottom_right = 20
    thickness = 30
    widget_spacing = 10

[brightness]
enable_ddcutil = true

[calendar]
enabled = true

[control_center]
width = 900

    [control_center.calendar]
    show_events_card = false

[dock]
background_opacity = 1
enabled = false

[hooks]
colors_changed = "systemctl --user try-restart xdg-desktop-portal.service xdg-desktop-portal-gtk.service"

[location]
address = "Galicia"

[notification]
background_opacity = 1

[osd]
background_opacity = 1

[plugins]
enabled = [ "noctalia/translator", "noctalia/mpvpaper" ]

[plugin_settings."noctalia/mpvpaper"]
picker_open_near_click = true
picker_placement = "attached"
video_directory = "~/.wallpaper-videos"

[shell]
font_family = "Adwaita Sans"
lang = "gl-ES"
launch_apps_as_systemd_services = true
polkit_agent = true
settings_show_advanced = true
telemetry_enabled = true

    [shell.greeter_sync]
    auto_sync = false

    [shell.launcher]
    app_grid = true

    [shell.panel]
    clipboard_placement = "attached"
    launcher_placement = "attached"
    open_near_click_clipboard = true
    open_near_click_control_center = true
    open_near_click_launcher = true
    open_near_click_session = true
    open_near_click_wallpaper = true

    [shell.screen_corners]
    enabled = true
    size = 20

    [shell.screenshot]
    directory = "~/Imaxes/Capturas de pantalla"

[system.monitor]
gpu_poll_seconds = 2
network_poll_seconds = 2

[theme]
builtin = "Tokyo-Night"
community_palette = "Neon Surf"
mode = "dark"
source = "wallpaper"
wallpaper_scheme = "vibrant"

    [theme.templates]
    builtin_ids = [
        "alacritty",
        "foot",
        "gtk3",
        "gtk4",
        "ghostty",
        "helix",
        "hyprland",
        "kcolorscheme",
        "kitty",
        "qt",
        "wezterm"
    ]
    community_ids = [
        "tauon",
        "zen-browser",
        "discord",
        "telegram",
        "neovim",
        "obsidian",
        "vscode",
        "zed",
        "prismlauncher",
        "steam",
        "obs",
        "zathura",
        "papirus-icons",
        "yazi",
        "hyprtoolkit"
    ]

        [theme.templates.user.ui-colors]
        input_path = "~/.local/share/gallaecia-dots/noctalia/ui-colors.sh.template"
        output_path = "~/.config/gallaecia-dots/ui-colors.sh"

[wallpaper]
directory = "~/.wallpapers"
transition = [ "disc" ]
transition_on_startup = true

    [wallpaper.default]
    path = "~/.wallpapers/Gallaecia - Torre de Hércules.jpg"

    [wallpaper.last]
    path = "~/.wallpapers/Gallaecia - Torre de Hércules.jpg"

[widget.media]
hide_when_no_media = true
title_scroll = "always"

[widget.mpvpaper]
type = "noctalia/mpvpaper:mpvpaper"

[widget.network]
show_label = false

[widget.system_update]
glyph = "cloud-download"
type = "custom_button"

    [widget.system_update.actions]
    left = "exec ~/.local/share/gallaecia-dots/scripts/run-terminal-as.sh system-update -- bash -lc ~/.local/share/gallaecia-dots/scripts/system-update.sh"
    middle = "exec ~/.local/share/gallaecia-dots/scripts/run-terminal-as.sh system-update -- bash -lc ~/.local/share/gallaecia-dots/scripts/system-update.sh"
    right = "exec ~/.local/share/gallaecia-dots/scripts/run-terminal-as.sh system-update -- bash -lc ~/.local/share/gallaecia-dots/scripts/system-update.sh"
