[bar.default]
background_opacity = 0.79999998211860657
center = [ "workspaces" ]
end = [
    "media",
    "tray",
    "notifications",
    "clipboard",
    "network",
    "bluetooth",
    "volume",
    "brightness",
    "battery",
    "session"
]
margin_edge = 0
margin_ends = 0
radius = 0
radius_bottom_left = -20
radius_bottom_right = -20
start = [ "clock", "launcher", "wallpaper" ]
widget_spacing = 8

[plugins]
enabled = []

[shell]
font_family = "Adwaita Sans"
launch_apps_as_systemd_services = true
polkit_agent = true
settings_show_advanced = true
telemetry_enabled = true

    [shell.launcher]
    app_grid = true

    [shell.panel]
    clipboard_placement = "attached"
    launcher_placement = "attached"
    open_near_click_clipboard = true
    open_near_click_control_center = true
    open_near_click_launcher = true
    open_near_click_session = true
    open_near_click_wallpaper = true

    [shell.screen_corners]
    enabled = true
    size = 20

[system.monitor]
gpu_poll_seconds = 2

[theme]
builtin = "Catppuccin"
mode = "dark"
source = "wallpaper"
wallpaper_scheme = "vibrant"

    [theme.templates]
    builtin_ids = [ "gtk3", "gtk4", "hyprland", "kitty", "qt" ]

[wallpaper]
directory = "~/.wallpapers"
transition = [ "disc" ]
transition_on_startup = true

[widget.media]
hide_when_no_media = true
title_scroll = "always"

[widget.network]
show_label = false
