[bar.default]
background_opacity = 0.99999997764825821
capsule_thickness = 0.79999998584389687
center = [ "workspaces" ]
end = [
    "media",
    "tray",
    "notifications",
    "clipboard",
    "network",
    "bluetooth",
    "volume",
    "brightness",
    "battery",
    "session"
]
font_family = "Adwaita Sans"
margin_edge = 0
margin_ends = 0
padding = 15
radius = 0
radius_bottom_left = -20
radius_bottom_right = -20
start = [ "clock", "launcher", "wallpaper", "system_update" ]
thickness = 30
widget_spacing = 10

[brightness]
enable_ddcutil = true

[calendar]
enabled = true

[control_center]
width = 900

[dock]
background_opacity = 0.99999997764825821

[notification]
background_opacity = 0.99999997764825821

[osd]
background_opacity = 0.99999997764825821

[plugins]
enabled = []

[shell]
font_family = "Adwaita Sans"
lang = "es"
launch_apps_as_systemd_services = true
polkit_agent = true
settings_show_advanced = true
telemetry_enabled = true

    [shell.greeter_sync]
    auto_sync = true

    [shell.launcher]
    app_grid = true

    [shell.panel]
    clipboard_placement = "attached"
    launcher_placement = "attached"
    open_near_click_clipboard = true
    open_near_click_control_center = true
    open_near_click_launcher = true
    open_near_click_session = true
    open_near_click_wallpaper = true

    [shell.screen_corners]
    enabled = true
    size = 20

    [shell.screenshot]
    directory = "$HOME/Imaxes/Capturas de pantalla"

[system.monitor]
gpu_poll_seconds = 2
network_poll_seconds = 2

[theme]
builtin = "Catppuccin"
mode = "dark"
source = "wallpaper"
wallpaper_scheme = "vibrant"

    [theme.templates]
    builtin_ids = [ "gtk3", "gtk4", "hyprland", "kitty", "qt" ]

[wallpaper]
directory = "$HOME/.wallpapers"
transition = [ "disc" ]
transition_on_startup = true

    [wallpaper.default]
    path = "$HOME/.wallpapers/Gallaecia - Torre de Hércules.jpg"

    [wallpaper.last]
    path = "$HOME/.wallpapers/Gallaecia - Torre de Hércules.jpg"

[widget.media]
hide_when_no_media = true
title_scroll = "always"

[widget.network]
show_label = false

[widget.system_update]
command = "kitty -e sh -c '$HOME/.config/gallaecia-dots/scripts/system-update.sh'"
glyph = "cloud-download"
middle_command = "kitty -e sh -c '$HOME/.config/gallaecia-dots/scripts/system-update.sh'"
right_command = "kitty -e sh -c '$HOME/.config/gallaecia-dots/scripts/system-update.sh'"
type = "custom_button"
